Traceback (most recent call last):
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/solver_fe_al.py", line 258, in training
    batch = next(data_iter)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1318, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/solver_fe_al.py", line 275, in training
    outputs_b, targets_b, _, _ = model(inputs=x_b, targets=y_b, coords=c_b, input_lengths=input_lengths, env_features=env_features, head_only=True, aux_answers=aux_y_b)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 636, in forward
    env_feature_Q = self.transformer_encoder(env_feature_Q)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 154, in forward
    e_outputs = self.encoder(src, mask=None, input_keep=None)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 144, in forward
    src = self.layers[i](src, mask, input_keep)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 30, in forward
    x = x + self.dropout_1(self.attn(x2, x2, x2, mask, input_keep))
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 106, in forward
    output = self.out(concat)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 1 has a total capacty of 31.73 GiB of which 3.88 MiB is free. Including non-PyTorch memory, this process has 31.71 GiB memory in use. Of the allocated memory 31.08 GiB is allocated by PyTorch, and 86.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Trainer_fe_al.py", line 66, in <module>
    train(job_id, settings)
  File "./Trainer_fe_al.py", line 23, in train
    list_total, list_err = solver.training(settings=settings, job_id=job_id)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/solver_fe_al.py", line 362, in training
    outputs_b, targets_b, aux_outputs_b, aux_targets_b = model(inputs=x_b, targets=y_b, coords=c_b, input_lengths=input_lengths, env_features=env_features, head_only=True, aux_answers=aux_y_b)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 636, in forward
    env_feature_Q = self.transformer_encoder(env_feature_Q)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 154, in forward
    e_outputs = self.encoder(src, mask=None, input_keep=None)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 144, in forward
    src = self.layers[i](src, mask, input_keep)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 30, in forward
    x = x + self.dropout_1(self.attn(x2, x2, x2, mask, input_keep))
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 103, in forward
    scores = ori_attention(q, k, v, self.d_k, mask, self.dropout, None)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model_fe_al.py", line 65, in ori_attention
    output = torch.matmul(scores, v)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 1 has a total capacty of 31.73 GiB of which 3.88 MiB is free. Including non-PyTorch memory, this process has 31.71 GiB memory in use. Of the allocated memory 31.08 GiB is allocated by PyTorch, and 86.06 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

