Traceback (most recent call last):
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/solver.py", line 139, in training
    batch = next(data_iter)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1318, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/solver.py", line 153, in training
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 641, in forward
    token_k = self.transformer_encoder(k_transformer_input, k_attention_mask, None)[:, 0, :]
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 153, in forward
    e_outputs = self.encoder(src, src_mask, input_keep)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 143, in forward
    src = self.layers[i](src, mask, input_keep)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 29, in forward
    x = x + self.dropout_1(self.attn(x2, x2, x2, mask, input_keep))
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 93, in forward
    v = self.v_linear(v).view(bs, -1, self.h, self.d_k)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 1 has a total capacty of 31.73 GiB of which 5.38 MiB is free. Including non-PyTorch memory, this process has 31.71 GiB memory in use. Of the allocated memory 31.11 GiB is allocated by PyTorch, and 47.58 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Trainer.py", line 66, in <module>
    train(job_id, settings)
  File "./Trainer.py", line 23, in train
    list_total, list_err = solver.training(settings=settings, job_id=job_id)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/solver.py", line 227, in training
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 628, in forward
    pe = self.spenc(coords)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 490, in forward
    return self.ffn(spr_embeds)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 401, in forward
    output = layer(output)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs/data5/home/kit/stud/uqqww/PEGNN_reg4/model.py", line 295, in forward
    output = self.linear(input_tensor)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kit/stud/uqqww/miniconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 1 has a total capacty of 31.73 GiB of which 5.38 MiB is free. Including non-PyTorch memory, this process has 31.71 GiB memory in use. Of the allocated memory 31.11 GiB is allocated by PyTorch, and 47.27 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

